### ISSUE TITLE
Issues on the execution of main command

### ISSUE THREAD

**Issue by yoplait** [vitobotta/hetzner-k3s#28]
Hi there! Looks like is not able to execute:

I did a clean and a docker attempt:

```
hetzner-k3s create-cluster --config-file=./cluster/test_filled.yaml 

________________________________________________________________________________
| ~/Documents/Code/ubloquity/terraform-k8s-hetzner-DigitalOcean-Federation/hetzner_03 @ jperez-mbp (jperez)
| => hetzner-k3s create-cluster --config-file=./cluster/test_filled.yaml

Firewall already exists, skipping.


Private network already exists, skipping.


Creating SSH key...
...SSH key created.

Traceback (most recent call last):
	10: from /usr/local/bin/hetzner-k3s:23:in `<main>'
	 9: from /usr/local/bin/hetzner-k3s:23:in `load'
	 8: from /Library/Ruby/Gems/2.6.0/gems/hetzner-k3s-0.4.2/exe/hetzner-k3s:4:in `<top (required)>'
	 7: from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	 6: from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 5: from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 4: from /Library/Ruby/Gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cli.rb:28:in `create_cluster'
	 2: from /Library/Ruby/Gems/2.6.0/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:39:in `create'
	 1: from /Library/Ruby/Gems/2.6.0/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:105:in `create_resources'
/Library/Ruby/Gems/2.6.0/gems/hetzner-k3s-0.4.2/lib/hetzner/infra/ssh_key.rb:26:in `create': undefined method `[]' for nil:NilClass (NoMethodError)
________________________________________________________________________________
| ~/Documents/Code/ubloquity/terraform-k8s-hetzner-DigitalOcean-Federation/hetzner_03 @ jperez-mbp (jperez)
```

What I am doing is a prev envsub 

```
envsubst < ./cluster/test.yaml | tee ./cluster/test_filled.yaml 
```

Where I am redacting:
```---
hetzner_token: 0lQ5BEtHPChange_me9YVUOSIiOj8Kt68LNM2bV
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa_no_pass.pub"
private_ssh_key_path: "~/.ssh/id_rsa_no_pass"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: hel1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 3
- name: big
  instance_type: cpx31
  instance_count: 2
```

Any ideas? Cheers!

**Comment by yoplait** [comment]
Just in case I just passed a lint

```
| => yamllint ./cluster/test_filled.yaml
```

**Comment by yoplait** [comment]
Thanks for the answer @vitobotta but mmmm already tried:

```
| => docker run --rm -it -v ${PWD}/cluster:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.4.2 create-cluster --config-file /cluster/test_filled.yaml
Enter passphrase for /root/.ssh/github_com_rsa:
Enter passphrase for /root/.ssh/gitlab_com_rsa:
Enter passphrase for /root/.ssh/google_compute_engine:
Enter passphrase for /root/.ssh/id_rsa:
Enter passphrase for /root/.ssh/ssh_rsa:

Firewall already exists, skipping.


Private network already exists, skipping.


SSH key already exists, skipping.


API load balancer already exists, skipping.









Server test-cpx21-master3 already exists, skipping.

Creating server test-cpx31-pool-big-worker1...
Server test-cpx21-master2 already exists, skipping.

Server test-cpx31-pool-big-worker2 already exists, skipping.

Creating server test-cpx21-pool-small-worker2...
Creating server test-cpx21-pool-small-worker1...
...server test-cpx31-pool-big-worker1 created.

Server test-cpx21-pool-small-worker3 already exists, skipping.

Server test-cpx21-master1 already exists, skipping.

...server test-cpx21-pool-small-worker1 created.

...server test-cpx21-pool-small-worker2 created.


Waiting for server test-cpx21-master3 to be up...
Waiting for server test-cpx31-pool-big-worker2 to be up...
#<Thread:0x00007fb4e255df18 /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:441:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:442:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
#<Thread:0x00007fb4e255da68 /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:441:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:442:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
Waiting for server test-cpx21-master2 to be up...
#<Thread:0x00007fb4e255d928 /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:441:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:442:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-pool-small-worker3 to be up...
...server test-cpx21-master1 is now up.
...server test-cpx31-pool-big-worker2 is now up.
...server test-cpx21-master2 is now up.
...server test-cpx21-pool-small-worker3 is now up.
...server test-cpx21-master3 is now up.
Traceback (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:154:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:441:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.2/lib/hetzner/k3s/cluster.rb:442:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
________________________________________________________________________________

```

**Comment by vitobotta** [comment]
Hi, have you tried leaving only the ssh key you want to use in the /.ssh directory? I am wondering if there is a problem when there are multiple keys.

**Comment by petaki** [comment]
@vitobotta Thanks for the fast response! Yes, I created a dedicated directory for SSH keys (`id_rsa`, `id_rsa.pub`) and I tried to mount this way from `${PWD}`:

```
docker run --rm -it -v ${PWD}:/cluster -v ${PWD}/ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.4.2 delete-cluster --config-file /cluster/hetzner-k3s.yaml
```

**Comment by vitobotta** [comment]
I found the problem and I am going to release a fix soon.

**Comment by vitobotta** [comment]
Just pushed 0.4.3. Can you give it a try?

**Comment by vitobotta** [comment]
I'm building the Docker image, it should be available in a few mins if you want to try with Docker.

**Comment by vitobotta** [comment]
The Docker image is now pushed. Please give it a try and let me know :)

**Comment by petaki** [comment]
I can't see the new tag :(
https://hub.docker.com/r/vitobotta/hetzner-k3s/tags

**Comment by vitobotta** [comment]
Oops I pushed 0.4.2 by mistake :p Try now :)

**Comment by petaki** [comment]
@vitobotta Thank you! It works! 💯  🎉

**Comment by vitobotta** [comment]
Awesome, thanks for confirming 👍
