### ISSUE TITLE
[Windows] Create cluster - No such file or directory

### ISSUE THREAD

**Issue by ludgart** [vitobotta/hetzner-k3s#48]
Hello,

the program stop in the cloud controller manager setup. Is there a way to fix it?

```
Deploying Hetzner Cloud Controller Manager...
Traceback (most recent call last):
        10: from C:/Ruby27-x64/bin/hetzner-k3s:23:in `<main>'
         9: from C:/Ruby27-x64/bin/hetzner-k3s:23:in `load'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/exe/hetzner-k3s:4:in `<top (required)>'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cli.rb:28:in `create_cluster'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:46:in `create'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:346:in `deploy_cloud_controller_manager'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:346:in `write': No such file or directory @ rb_sysopen - /tmp/cloud-controller-manager.yaml (Errno::ENOENT)
```

Thanks in advance!

Regards
ludgart

**Comment by vitobotta** [comment]
Hi, it looks like you're on Windows. The tool isn't tested on Windows as I don't have a Windows computer. The problem as you can see in the error is that it's writing a temporary file to /tmp, which doesn't exist on Windows.

You can use the Docker image though on any operating system and it works the same. There's only a small difference in the configuration file, see README about this.

**Comment by ludgart** [comment]
Thank you for your information! I found a workaround. Simple, create a tmp folder on your system driver, mostly C.

With CMD:
```
mkdir C:\tmp
```

**Comment by vitobotta** [comment]
Glad it works :)
