### ISSUE TITLE
Question: how to pass extra-args to new K3S cluster's components?

### ISSUE THREAD

**Issue by ferdinandosimonetti** [vitobotta/hetzner-k3s#63]
Hello, let's say that I need to prepare a K3S cluster with specific features enabled from the start:
- **EphemeralContainers** support
- Mount of underlying server's **/etc/localtime** to **kube-controller-manager**'s **/etc/localtime** (allowing **CronJob**'s schedules to be consistent with local timezone)

With RKE clusters, I'd specify these settings inside **cluster.yml** cluster definition, as shown below.
How can I perform similar pre-configuration with your tool?
Thanks in advance

```    kube-api:
      always_pull_images: false
      extra_args:
        feature-gates: EphemeralContainers=true
      pod_security_policy: false
      secrets_encryption_config:
        enabled: true
      service_node_port_range: 30000-32767
    kube-controller:
      extra_binds:
        - '/etc/localtime:/etc/localtime'
    kubelet:
      extra_args:
        feature-gates: EphemeralContainers=true
        protect-kernel-defaults: 'true'
      fail_swap_on: true
      generate_serving_certificate: true
    kubeproxy: {}
    scheduler:
      extra_args:
        feature-gates: EphemeralContainers=true ```

**Comment by vitobotta** [comment]
At the moment these two are not supported because I have never needed them, but it should be possible to add at least the option for extra args. Not sure about mounting /etc/localtime. I've added notes to the board so I can look into them when I have more time https://github.com/vitobotta/hetzner-k3s/projects/1#card-77823056 and https://github.com/vitobotta/hetzner-k3s/projects/1#card-77823070.

**Comment by vitobotta** [comment]
Hi, I've released v0.5.4 that allows you to specify extra arguments for every Kubernetes controller with this additional configuration:

```yaml
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...
```

This way you can enable feature flags etc. Unfortunately it doesn't seem possible to configure extra binds (for /etc/localtime) with k3s, so I don't think the other request is possible at this time. Can you please try creating a cluster with extra args and letting me know if you run into issues? Please note that if any of the extra args you specify are not valid, k3s will fail to start.

**Comment by ferdinandosimonetti** [comment]
Hello Vito, thanks a lot, but now I'm hitting this error
```
ferdi@ferdi-U820:~/r0$ docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.5.4 create-cluster --config-file /cluster/r0-config.yml
/usr/local/bundle/gems/hetzner-k3s-0.5.4/lib/hetzner/k3s/cli.rb:371:in `validate_create': undefined local variable or method `validate_network_zone' for #<Hetzner::K3s::CLI:0x00007fabf91755c8 @errors=[[]], @used_server_types=["cpx21"], @_invocations={Hetzner::K3s::CLI=>["create_cluster"]}, @_initializer=[[], ["--config-file", "/cluster/r0-config.yml"], {:shell=>#<Thor::Shell::Color:0x00007fabf9175f50 @base=#<Hetzner::K3s::CLI:0x00007fabf91755c8 ...>, @mute=false, @padding=0, @always_force=false>, :current_command=>#<struct Thor::Command name="create_cluster", description="Create a k3s cluster in Hetzner Cloud", long_description=nil, usage="create-cluster", options={:config_file=>#<Thor::Option:0x00007fabf91b4570 @check_default_type=nil, @repeatable=false, @name="config_file", @description=nil, @required=true, @type=:string, @default=nil, @human_name="config_file", @banner="CONFIG_FILE", @enum=nil, @lazy_default=nil, @aliases=[], @hide=nil, @switch_name="--config-file">}, ancestor_name=nil>}], @options={"config_file"=>"/cluster/r0-config.yml"}, @args=[], @shell=#<Thor::Shell::Color:0x00007fabf9175f50 @base=#<Hetzner::K3s::CLI:0x00007fabf91755c8 ...>, @mute=false, @padding=0, @always_force=false>, @configuration={"hetzner_token"=>"Ed5H4ZsrXSuH2exiHPWfXPLVJZpsOKvgZOeaItCVfSBZJ0RiEReY6GsgGQ85jKkb", "cluster_name"=>"r0", "k3s_version"=>"v1.23.2+k3s1", "kubeconfig_path"=>"/cluster/r0-kubeconfig", "public_ssh_key_path"=>"/tmp/.ssh/id_ed25519.pub", "private_ssh_key_path"=>"/tmp/.ssh/id_ed25519", "ssh_allowed_networks"=>["0.0.0.0/0"], "verify_host_key"=>false, "location"=>"nbg1", "schedule_workloads_on_masters"=>true, "masters"=>{"instance_type"=>"cpx21", "instance_count"=>1}, "enable_ipsec_encryption"=>true, "kube_apiserver_args"=>["feature-gates=EphemeralContainers=true"], "kubelet_args"=>["feature-gates=EphemeralContainers=true"], "kube_proxy_args"=>["feature-gates=EphemeralContainers=true"], "kube_controller_manager_args"=>["feature-gates=EphemeralContainers=true"]}, @token="Ed5H4ZsrXSuH2exiHPWfXPLVJZpsOKvgZOeaItCVfSBZJ0RiEReY6GsgGQ85jKkb", @hetzner_client=#<Hetzner::Client:0x00007fabf91948d8 @token="Ed5H4ZsrXSuH2exiHPWfXPLVJZpsOKvgZOeaItCVfSBZJ0RiEReY6GsgGQ85jKkb">, @valid=true, @locations=["fsn1", "nbg1", "hel1", "ash"], @available_releases=["v1.23.3+k3s1", "v1.23.3-rc1+k3s1", "v1.23.2+k3s1", "v1.23.2-rc1+k3s1", "v1.23.1+k3s2", "v1.23.1+k3s1", "v1.23.1-rc2+k3s2", "v1.23.1-rc1+k3s2", "v1.23.1-rc1+k3s1", "v1.22.7-rc1+k3s1", "v1.22.6+k3s1", "v1.22.6-rc1+k3s1", "v1.22.5+k3s2", "v1.22.5+k3s1", "v1.22.5-rc2+k3s2", "v1.22.5-rc2+k3s1", "v1.22.5-rc1+k3s2", "v1.22.5-rc1+k3s1", "v1.22.4+k3s1", "v1.22.4-rc3+k3s2", "v1.22.4-rc2+k3s2", "v1.22.4-rc2+k3s1", "v1.22.4-rc1+k3s2", "v1.22.4-rc1+k3s1", "v1.22.3+k3s1", "v1.22.3-rc4+k3s1", "v1.22.3-rc3+k3s1", "v1.22.3-rc2+k3s1", "v1.22.3-rc1+k3s1", "v1.22.2+k3s2", "v1.22.2+k3s1", "v1.22.2-rc3+k3s1", "v1.22.2-rc2+k3s1", "v1.22.2-rc1+k3s2", "v1.22.2-rc1+k3s1", "v1.22.1-rc1+k3s1", "v1.21.10-rc1+k3s1", "v1.21.9+k3s1", "v1.21.9-rc1+k3s1", "v1.21.9-engine0+k3s1", "v1.21.8+k3s2", "v1.21.8+k3s1", "v1.21.8-rc2+k3s2", "v1.21.8-rc2+k3s1", "v1.21.8-rc1+k3s2", "v1.21.8-rc1+k3s1", "v1.21.8-engine0+k3s2", "v1.21.8-engine0+k3s1", "v1.21.7+k3s1", "v1.21.7-rc2+k3s2", "v1.21.7-rc2+k3s1", "v1.21.7-rc1+k3s2", "v1.21.7-rc1+k3s1", "v1.21.7-engine0+k3s1", "v1.21.6+k3s1", "v1.21.6-rc3+k3s1", "v1.21.6-rc2+k3s1", "v1.21.6-rc1+k3s1", "v1.21.5+k3s2", "v1.21.5+k3s1", "v1.21.5-rc1+k3s2", "v1.21.5-rc1+k3s1", "v1.21.5-engine0+k3s1", "v1.21.4+k3s1", "v1.21.4-rc1+k3s1", "v1.21.4-engine0+k3s1", "v1.21.3+k3s1", "v1.21.3-rc3+k3s1", "v1.21.3-rc2+k3s1", "v1.21.3-rc1+k3s1", "v1.21.2+k3s1", "v1.21.2-rc2+k3s2", "v1.21.2-rc1+k3s2", "v1.21.2-rc1+k3s1", "v1.21.1+k3s1", "v1.21.1-rc2+k3s1", "v1.21.1-rc1+k3s1", "v1.21.0+k3s1", "v1.21.0-rc1+k3s1", "v1.21.0-alpha1+k3s1", "v1.20.15+k3s1", "v1.20.15-rc1+k3s1", "v1.20.14+k3s2", "v1.20.14+k3s1", "v1.20.14-rc2+k3s1", "v1.20.14-rc1+k3s2", "v1.20.14-rc1+k3s1", "v1.20.13+k3s1", "v1.20.13-rc2+k3s2", "v1.20.13-rc2+k3s1", "v1.20.13-rc1+k3s2", "v1.20.13-rc1+k3s1", "v1.20.12+k3s1", "v1.20.12-rc2+k3s1", "v1.20.12-rc1+k3s1", "v1.20.11+k3s2", "v1.20.11+k3s1", "v1.20.11-rc1+k3s2", "v1.20.11-rc1+k3s1", "v1.20.10+k3s1"], @server_types=["cx11", "cx21", "cx31", "cx41", "cx51", "ccx11", "ccx21", "ccx31", "ccx41", "ccx51", "cpx11", "cpx21", "cpx31", "cpx41", "cpx51", "ccx12", "ccx22", "ccx32", "ccx42", "ccx52", "ccx62"]> (NameError)

        validate_network_zone
        ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  validate_token
	from /usr/local/bundle/gems/hetzner-k3s-0.5.4/lib/hetzner/k3s/cli.rb:77:in `validate_configuration'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.4/lib/hetzner/k3s/cli.rb:35:in `create_cluster'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.4/exe/hetzner-k3s:4:in `<top (required)>'
	from /usr/local/bundle/bin/hetzner-k3s:25:in `load'
	from /usr/local/bundle/bin/hetzner-k3s:25:in `<main>'
```
using the attached (token has been sanitized, of course) config file.
I've tried to add "validate_network_zone: false" to the config file, but it wasn't useful.

[r0-config.txt](https://github.com/vitobotta/hetzner-k3s/files/8114740/r0-config.txt)

**Comment by vitobotta** [comment]
Thanks for reporting, I had to remove some leftover following other changes from yesterda. I have released v0.5.5 for this, please try again.

**Comment by ferdinandosimonetti** [comment]
Yes! It works! Thank you! I think that this addition could be useful for others, too.

```
[r0|default] ferdi@ferdi-U820:~/r0$ kubectl run --image=nginx:latest prova
pod/prova created
[r0|default] ferdi@ferdi-U820:~/r0$ kubectl get po
NAME    READY   STATUS    RESTARTS   AGE
prova   1/1     Running   0          47s
[r0|default] ferdi@ferdi-U820:~/r0$ kubectl debug -it prova --image=rimmon1971/myalpine:3.14.2 --target=prova --image-pull-policy='Always'
Targeting container "prova". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-bkqn2.

If you don't see a command prompt, try pressing enter.

bash-5.1# ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 nginx: master process nginx -g daemon off;
   31 101       0:00 nginx: worker process
   32 101       0:00 nginx: worker process
   33 101       0:00 nginx: worker process
   34 root      0:00 /bin/bash
   41 root      0:00 ps -ef
bash-5.1# 
```

**Comment by vitobotta** [comment]
Yeah thanks again for pointing out. I removed part of the leftover after releasing yesterday but I forgot to test again, so that remaining bit was still there.

**Comment by vitobotta** [comment]
I agree that this addition can be very useful in a number of scenarios.
