### ISSUE TITLE
Create cluster fails `undefined method `[]' for nil:NilClass (NoMethodError)` 

### ISSUE THREAD

**Issue by sananguliyev** [vitobotta/hetzner-k3s#82]
Version: `v0.5.7`
Error: 

```
...k3s has been deployed to worker (prod-cpx21-pool-small-worker1).

#<Thread:0x00007fb1a12964e0 /usr/local/bundle/gems/hetzner-k3s-0.5.7/lib/hetzner/k3s/cluster.rb:273 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/ed25519.rb:80:in `read': undefined method `[]' for nil:NilClass (NoMethodError)

            cipher = CipherFactory.get(ciphername, key: key[0...keylen], iv:key[keylen...keylen + ivlen], decrypt: true)
                                                           ^^^^^^^^^^^^
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:125:in `read'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:59:in `load_data_private_key'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:42:in `load_private_key'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:167:in `sign'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:132:in `block in each_identity'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:129:in `each'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:129:in `each_identity'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
        from /usr/local/bundle/gems/hetzner-k3s-0.5.7/lib/hetzner/utils.rb:82:in `ssh'
        from /usr/local/bundle/gems/hetzner-k3s-0.5.7/lib/hetzner/k3s/cluster.rb:277:in `block (2 levels) in deploy_kubernetes'
/usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/ed25519.rb:80:in `read': undefined method `[]' for nil:NilClass (NoMethodError)

            cipher = CipherFactory.get(ciphername, key: key[0...keylen], iv:key[keylen...keylen + ivlen], decrypt: true)
                                                           ^^^^^^^^^^^^
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:125:in `read'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:59:in `load_data_private_key'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/key_factory.rb:42:in `load_private_key'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:167:in `sign'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:132:in `block in each_identity'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:129:in `each'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:129:in `each_identity'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
        from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
        from /usr/local/bundle/gems/hetzner-k3s-0.5.7/lib/hetzner/utils.rb:82:in `ssh'
        from /usr/local/bundle/gems/hetzner-k3s-0.5.7/lib/hetzner/k3s/cluster.rb:277:in `block (2 levels) in deploy_kubernetes'
```

**Comment by sananguliyev** [comment]
This most probably caused by wrong configuration.
